name: advent2021
description: >-
  Advent fo Code 2021 Solutions
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  sortedmap: ^0.5.1
  tuple: ^2.0.0

dev_dependencies:
  test: '>=1.15.0 <2.0.0'